  // Client configs...
  const clientConfig = {
    maximos: {
      label: "St. Maximos the Confessor",
      labelColor: "#000000",
      backgroundImage: "url('/maximos2.jpg')",
      fontFamily: "'Lato', sans-serif",
      placeholder: "Seek counsel from St. Maximos...",
      backgroundOpacity: 3,
      showSources: false,
      showFeedback: false,
    },
    ordinance: {
      label: "Anytown USA Ordinance",
      labelColor: "#000000",
      backgroundImage: "url('/midwestsummer.jpg')",
      fontFamily: "'Montserrat', sans-serif",
      placeholder: "Ask about Anytown USA Ordinance...",
      backgroundOpacity: 3,
      showSources: false,
      showFeedback: true,
    },
    marketingasst: {
      label: "Parish Marketing Assistant",
      labelColor: "#000000",
      backgroundColor: "#f9ca24",
      fontFamily: "'Lato', sans-serif",
      placeholder: "How can we help you today?",
      backgroundOpacity: 1,
      showSources: false,
      showFeedback: false,
    },
    samuel: {
      label: "Samuel Kelly - A Real 18th Century Sailor",
      labelColor: "#000000",
      backgroundImage: "url('/samuel2.jpg')",
      fontFamily: "'Montserrat', sans-serif",
      placeholder: "Ask Samuel Kelly anything...",
      backgroundOpacity: 1,
      showSources: false,
      showFeedback: false,
    },
    prairiepastorate: {
      label: "Prairie Catholic Pastorate Assistant",
      labelColor: "#000000",
      backgroundImage: "url('/church.jpg')",
      fontFamily: "'Lato', sans-serif",
      placeholder: "How can I help you?",
      backgroundOpacity: 1,
      showSources: false,
      showFeedback: true,
    },
  };
  export default clientConfig;